version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - '3001:3001'
